# Generated by Django 4.2.2 on 2023-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agctl', '0002_connectedagent_delete_connectagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=64)),
                ('other_info', models.TextField()),
            ],
        ),
    ]
