# Generated by Django 4.2.2 on 2023-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agctl', '0004_device_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='mac_address',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='device',
            name='product_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
