# Generated by Django 4.2.2 on 2023-06-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agctl', '0005_rename_mac_address_device_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agctl.connectedagent'),
        ),
    ]
