# Generated by Django 4.2.2 on 2023-06-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agctl', '0006_device_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agctl.connectedagent'),
        ),
    ]
